# =============================================
# BASE DE DATOS EMBEBIDA H2 (no necesita MySQL)
# Los datos se guardan en archivo: inventario_db.mv.db
# =============================================
spring.datasource.url=jdbc:h2:file:./data/inventario_db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2 (ver base de datos en navegador: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Puerto
server.port=8080
